CREATE TABLE cvcrm.lead_report_ (
 id serial,
 id_report int8 NULL,
 situacao varchar(50),
 situacaoanterior varchar(50),
 datahoraprimeirocadastro timestamp,
 Nome varchar(150),
 email varchar(150),
 telefone varchar(150),
 pontovenda varchar(100),
 empreendimento varchar(150),
 primeiroempreendimento varchar(100),
 ultimoempreendimento varchar(100),
 codigointerno varchar(50),
 precadastros int4 null,
 reserva int4 null,
 simulacao int4 null,
 ganhos int4 null,
 perdas int4 null,
 totalvencimentos int4 null,
 gestorprimeiro varchar(100),
 gestorultimo varchar(100),
 gestor varchar(100),
 corretor varchar(100),
 categoriacorretor varchar(100),
 nivelcorretor varchar(100),
 imobiliariaprimeira varchar(100),
 imobiliariaultima varchar(100),
 imobiliaria varchar(100),
 corretoranterior varchar(100),
 penultimocorretor varchar(100),
 primeiraorigem varchar(100),
 ultimaorigem varchar(100),
 produtolead varchar(150),
 motivocancelamento varchar(100),
 descricaomotivocancelamento varchar(400),
 datacancelamento date,
 dataprimeirainteracaogestor_sdr date,
 dataprimeirainteracaocorretor date,
 dataultimainteracao date,
 dataenviocorretoranterior date,
 dataenviocorretor date,
 diassemcontato int4 null,
 datareativacao date,
 leadvencido varchar(150),
 primeiramidia varchar(150),
 ultimamidia varchar(150),
 possibilidade varchar(150),
 primeiraconversao varchar(150),
 ultimaconversao varchar(150),
 emailalternativo varchar(150),
 sexo varchar(40),
 profissao varchar(100),
 datanascimento date,
 telefonealternativo varchar(150),
 cep varchar(30),
 endereco varchar(150),
 numero varchar(50),
 complemento varchar(150),
 bairro varchar(100),
 estado varchar(50),
 cidade varchar(100),
 documento varchar(100),
 renda varchar(100),
 tag varchar(150),
 tempoconversaoreserva varchar(100),
 tempoconversaovenda varchar(100),
 primeiracampanha varchar(150),
 ultimacampanha varchar(150),
 dataultimaalteracaosituacao date,
 origemrd varchar(150),
 bolsao varchar(150),
 momentolead varchar(150),
 create_datetime timestamp NULL DEFAULT now(),
 hb_midia_lote_id int4 NULL
);